CREATE TABLE "GCG_6237_Unit_Price"(
 "CUSTOMER" CHAR(6),
 "PART" CHAR(20),
 "LOCATION" CHAR(2),
 "MAX_PALLET" INTEGER,
 "UNIT_PRICE" DOUBLE);

CREATE INDEX "GCG_6237_Unit_Price" ON "GCG_6237_Unit_Price"("CUSTOMER","PART", "LOCATION");