CREATE TABLE "GCG_6237_Ord_Disc"(
 "ORDER_NO" CHAR(6),
 "RECORD_NO" CHAR(4),
 "PART" CHAR(20),
 "LOCATION" CHAR(2));

CREATE INDEX "GCG_6237_Ord_Disc" ON "GCG_6237_Ord_Disc"("ORDER_NO","PART", "LOCATION");